In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook
import requests

In [5]:
data = pd.read_csv("/data/workspace_files/crypto.csv")

In [6]:
data.head()

,Unnamed: 0,Coin,Exchange,open,high,low,close,volume,Coin.1,Exchange.1,...,low.48,close.48,volume.48,Coin.49,Exchange.49,open.49,high.49,low.49,close.49,volume.49
0,2014-07-23 19:00:00,BTC,Coinbase,NaN,NaN,NaN,NaN,NaN,BTC,Bittrex,...,NaN,NaN,NaN,XTZ,Gemini,NaN,NaN,NaN,NaN,NaN
1,2014-07-23 20:00:00,BTC,Coinbase,NaN,NaN,NaN,NaN,NaN,BTC,Bittrex,...,NaN,NaN,NaN,XTZ,Gemini,NaN,NaN,NaN,NaN,NaN
2,2014-07-23 21:00:00,BTC,Coinbase,NaN,NaN,NaN,NaN,NaN,BTC,Bittrex,...,NaN,NaN,NaN,XTZ,Gemini,NaN,NaN,NaN,NaN,NaN
3,2014-07-23 22:00:00,BTC,Coinbase,NaN,NaN,NaN,NaN,NaN,BTC,Bittrex,...,NaN,NaN,NaN,XTZ,Gemini,NaN,NaN,NaN,NaN,NaN
4,2014-07-23 23:00:00,BTC,Coinbase,NaN,NaN,NaN,NaN,NaN,BTC,Bittrex,...,NaN,NaN,NaN,XTZ,Gemini,NaN,NaN,NaN,NaN,NaN

In [7]:
data.columns

Index(['Unnamed: 0', 'Coin', 'Exchange', 'open', 'high', 'low', 'close',
       'volume', 'Coin.1', 'Exchange.1',
       ...
       'low.48', 'close.48', 'volume.48', 'Coin.49', 'Exchange.49', 'open.49',
       'high.49', 'low.49', 'close.49', 'volume.49'],
      dtype='object', length=351)

In [8]:
## Generic data transformation functions 
data = data.rename(columns = {"Unnamed: 0": "Date"})

In [9]:
data.head()

,Date,Coin,Exchange,open,high,low,close,volume,Coin.1,Exchange.1,...,low.48,close.48,volume.48,Coin.49,Exchange.49,open.49,high.49,low.49,close.49,volume.49
0,2014-07-23 19:00:00,BTC,Coinbase,NaN,NaN,NaN,NaN,NaN,BTC,Bittrex,...,NaN,NaN,NaN,XTZ,Gemini,NaN,NaN,NaN,NaN,NaN
1,2014-07-23 20:00:00,BTC,Coinbase,NaN,NaN,NaN,NaN,NaN,BTC,Bittrex,...,NaN,NaN,NaN,XTZ,Gemini,NaN,NaN,NaN,NaN,NaN
2,2014-07-23 21:00:00,BTC,Coinbase,NaN,NaN,NaN,NaN,NaN,BTC,Bittrex,...,NaN,NaN,NaN,XTZ,Gemini,NaN,NaN,NaN,NaN,NaN
3,2014-07-23 22:00:00,BTC,Coinbase,NaN,NaN,NaN,NaN,NaN,BTC,Bittrex,...,NaN,NaN,NaN,XTZ,Gemini,NaN,NaN,NaN,NaN,NaN
4,2014-07-23 23:00:00,BTC,Coinbase,NaN,NaN,NaN,NaN,NaN,BTC,Bittrex,...,NaN,NaN,NaN,XTZ,Gemini,NaN,NaN,NaN,NaN,NaN

In [10]:
## Get column names
col_list = data.columns.tolist()

In [11]:
## Get all coin columns and exchange columns
coin_col = [x for x in col_list if "Coin" in x]
exchange_col = [x for x in col_list if "Exchange" in x]

In [12]:
data[exchange_col].head()

,Exchange,Exchange.1,Exchange.2,Exchange.3,Exchange.4,Exchange.5,Exchange.6,Exchange.7,Exchange.8,Exchange.9,...,Exchange.40,Exchange.41,Exchange.42,Exchange.43,Exchange.44,Exchange.45,Exchange.46,Exchange.47,Exchange.48,Exchange.49
0,Coinbase,Bittrex,Bitstamp,Kraken,Gemini,Coinbase,Bittrex,Bitstamp,Kraken,Gemini,...,Coinbase,Bittrex,Bitstamp,Kraken,Gemini,Coinbase,Bittrex,Bitstamp,Kraken,Gemini
1,Coinbase,Bittrex,Bitstamp,Kraken,Gemini,Coinbase,Bittrex,Bitstamp,Kraken,Gemini,...,Coinbase,Bittrex,Bitstamp,Kraken,Gemini,Coinbase,Bittrex,Bitstamp,Kraken,Gemini
2,Coinbase,Bittrex,Bitstamp,Kraken,Gemini,Coinbase,Bittrex,Bitstamp,Kraken,Gemini,...,Coinbase,Bittrex,Bitstamp,Kraken,Gemini,Coinbase,Bittrex,Bitstamp,Kraken,Gemini
3,Coinbase,Bittrex,Bitstamp,Kraken,Gemini,Coinbase,Bittrex,Bitstamp,Kraken,Gemini,...,Coinbase,Bittrex,Bitstamp,Kraken,Gemini,Coinbase,Bittrex,Bitstamp,Kraken,Gemini
4,Coinbase,Bittrex,Bitstamp,Kraken,Gemini,Coinbase,Bittrex,Bitstamp,Kraken,Gemini,...,Coinbase,Bittrex,Bitstamp,Kraken,Gemini,Coinbase,Bittrex,Bitstamp,Kraken,Gemini

In [13]:
data[coin_col]

,Coin,Coin.1,Coin.2,Coin.3,Coin.4,Coin.5,Coin.6,Coin.7,Coin.8,Coin.9,...,Coin.40,Coin.41,Coin.42,Coin.43,Coin.44,Coin.45,Coin.46,Coin.47,Coin.48,Coin.49
0,BTC,BTC,BTC,BTC,BTC,XRP,XRP,XRP,XRP,XRP,...,ADA,ADA,ADA,ADA,ADA,XTZ,XTZ,XTZ,XTZ,XTZ
1,BTC,BTC,BTC,BTC,BTC,XRP,XRP,XRP,XRP,XRP,...,ADA,ADA,ADA,ADA,ADA,XTZ,XTZ,XTZ,XTZ,XTZ
2,BTC,BTC,BTC,BTC,BTC,XRP,XRP,XRP,XRP,XRP,...,ADA,ADA,ADA,ADA,ADA,XTZ,XTZ,XTZ,XTZ,XTZ
3,BTC,BTC,BTC,BTC,BTC,XRP,XRP,XRP,XRP,XRP,...,ADA,ADA,ADA,ADA,ADA,XTZ,XTZ,XTZ,XTZ,XTZ
4,BTC,BTC,BTC,BTC,BTC,XRP,XRP,XRP,XRP,XRP,...,ADA,ADA,ADA,ADA,ADA,XTZ,XTZ,XTZ,XTZ,XTZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44013,BTC,BTC,BTC,BTC,BTC,XRP,XRP,XRP,XRP,XRP,...,ADA,ADA,ADA,ADA,ADA,XTZ,XTZ,XTZ,XTZ,XTZ
44014,BTC,BTC,BTC,BTC,BTC,XRP,XRP,XRP,XRP,XRP,...,ADA,ADA,ADA,ADA,ADA,XTZ,XTZ,XTZ,XTZ,XTZ
44015,BTC,BTC,BTC,BTC,BTC,XRP,XRP,XRP,XRP,XRP,...,ADA,ADA,ADA,ADA,ADA,XTZ,XTZ,XTZ,XTZ,XTZ
44016,BTC,BTC,BTC,BTC,BTC,XRP,XRP,XRP,XRP,XRP,...,ADA,ADA,ADA,ADA,ADA,XTZ,XTZ,XTZ,XTZ,XTZ
44017,BTC,BTC,BTC,BTC,BTC,XRP,XRP,XRP,XRP,XRP,...,ADA,ADA,ADA,ADA,ADA,XTZ,XTZ,XTZ,XTZ,XTZ

In [14]:
## Select a coin that is present across all exchanges
unique_coins = data[coin_col].iloc[0].unique().tolist()

In [15]:
data.columns.tolist().index(
"volume.4")

35

In [16]:
btc = data[data.columns.tolist()[:36]]

In [17]:
btc.head(10)

,Date,Coin,Exchange,open,high,low,close,volume,Coin.1,Exchange.1,...,low.3,close.3,volume.3,Coin.4,Exchange.4,open.4,high.4,low.4,close.4,volume.4
0,2014-07-23 19:00:00,BTC,Coinbase,NaN,NaN,NaN,NaN,NaN,BTC,Bittrex,...,605.68,605.68,NaN,BTC,Gemini,NaN,NaN,NaN,NaN,NaN
1,2014-07-23 20:00:00,BTC,Coinbase,NaN,NaN,NaN,NaN,NaN,BTC,Bittrex,...,605.68,605.68,NaN,BTC,Gemini,NaN,NaN,NaN,NaN,NaN
2,2014-07-23 21:00:00,BTC,Coinbase,NaN,NaN,NaN,NaN,NaN,BTC,Bittrex,...,605.64,605.64,624.12,BTC,Gemini,NaN,NaN,NaN,NaN,NaN
3,2014-07-23 22:00:00,BTC,Coinbase,NaN,NaN,NaN,NaN,NaN,BTC,Bittrex,...,605.64,605.64,NaN,BTC,Gemini,NaN,NaN,NaN,NaN,NaN
4,2014-07-23 23:00:00,BTC,Coinbase,NaN,NaN,NaN,NaN,NaN,BTC,Bittrex,...,605.64,605.64,NaN,BTC,Gemini,NaN,NaN,NaN,NaN,NaN
5,2014-07-24 00:00:00,BTC,Coinbase,NaN,NaN,NaN,NaN,NaN,BTC,Bittrex,...,605.64,605.64,NaN,BTC,Gemini,NaN,NaN,NaN,NaN,NaN
6,2014-07-24 01:00:00,BTC,Coinbase,NaN,NaN,NaN,NaN,NaN,BTC,Bittrex,...,605.64,605.64,NaN,BTC,Gemini,NaN,NaN,NaN,NaN,NaN
7,2014-07-24 02:00:00,BTC,Coinbase,NaN,NaN,NaN,NaN,NaN,BTC,Bittrex,...,605.64,605.64,NaN,BTC,Gemini,NaN,NaN,NaN,NaN,NaN
8,2014-07-24 03:00:00,BTC,Coinbase,NaN,NaN,NaN,NaN,NaN,BTC,Bittrex,...,605.64,605.64,NaN,BTC,Gemini,NaN,NaN,NaN,NaN,NaN
9,2014-07-24 04:00:00,BTC,Coinbase,NaN,NaN,NaN,NaN,NaN,BTC,Bittrex,...,605.64,605.64,NaN,BTC,Gemini,NaN,NaN,NaN,NaN,NaN

In [18]:
btc=btc.fillna(0)
btc.tail(10)

,Date,Coin,Exchange,open,high,low,close,volume,Coin.1,Exchange.1,...,low.3,close.3,volume.3,Coin.4,Exchange.4,open.4,high.4,low.4,close.4,volume.4
44008,2019-07-31 11:00:00,BTC,Coinbase,9968.00,10100.00,9967.33,10054.99,10562899.69,BTC,Bittrex,...,9965.5,10054.1,5597171.12,BTC,Gemini,9970.78,10091.13,9970.78,10057.66,2151456.31
44009,2019-07-31 12:00:00,BTC,Coinbase,10054.99,10135.12,9959.01,9989.28,11614097.22,BTC,Bittrex,...,9958.6,9982.6,6186201.45,BTC,Gemini,10057.66,10130.58,9959.13,9984.84,1303626.43
44010,2019-07-31 13:00:00,BTC,Coinbase,9989.28,10042.04,9974.31,10031.04,6844243.88,BTC,Bittrex,...,9967.7,10024.9,2276138.92,BTC,Gemini,9984.84,10041.79,9975.00,10031.28,844080.43
44011,2019-07-31 14:00:00,BTC,Coinbase,10031.04,10032.49,9947.12,9981.59,6497006.43,BTC,Bittrex,...,9950.0,9985.2,2391062.12,BTC,Gemini,10031.28,10034.95,9951.74,9985.10,582914.08
44012,2019-07-31 15:00:00,BTC,Coinbase,9981.59,10009.00,9978.50,9997.53,2818843.30,BTC,Bittrex,...,9985.0,9997.5,2111315.79,BTC,Gemini,9985.10,10017.69,9984.51,9999.00,170603.58
44013,2019-07-31 16:00:00,BTC,Coinbase,9997.53,10069.99,9997.52,10026.00,5873166.61,BTC,Bittrex,...,9997.5,10020.6,1671801.43,BTC,Gemini,9999.00,10075.32,9999.00,10024.41,299117.64
44014,2019-07-31 17:00:00,BTC,Coinbase,10026.00,10049.89,10007.51,10041.84,3620923.19,BTC,Bittrex,...,10020.0,10054.7,2287190.53,BTC,Gemini,10024.41,10061.46,10007.19,10050.71,494567.55
44015,2019-07-31 18:00:00,BTC,Coinbase,10041.84,10041.84,9981.06,10009.72,4263588.86,BTC,Bittrex,...,9978.0,10007.8,1883145.13,BTC,Gemini,10050.71,10060.66,9982.06,10018.30,509409.24
44016,2019-07-31 19:00:00,BTC,Coinbase,10009.72,10099.00,10002.33,10087.30,8364101.49,BTC,Bittrex,...,10000.6,10090.1,2351347.95,BTC,Gemini,10018.30,10099.00,10003.39,10079.54,273533.51
44017,2019-07-31 20:00:00,BTC,Coinbase,10087.30,10166.98,10036.83,10048.44,10725749.22,BTC,Bittrex,...,10037.2,10041.4,3369119.86,BTC,Gemini,10079.54,10168.00,10042.03,10059.05,643729.27

In [19]:
weighted_price = btc['close']*btc['volume']+btc['close.1']*btc['volume.1']+btc['close.2']*btc['volume.2']+btc['close.3']*btc['volume.3']+btc['close.4']*btc['volume.4']
total_volume =  btc['volume']+btc['volume.1']+btc['volume.2']+btc['volume.3']+btc['volume.4']
weighted_price = weighted_price/total_volume
weighted_price.head(10)
weighted_price = weighted_price.fillna(method='ffill')
weighted_price = weighted_price.fillna(method='bfill')
weighted_price

In [20]:

total_volume

In [21]:
features = pd.DataFrame([btc['Date'],weighted_price,total_volume],index=['Date','Weighted Volume Price','Total Volume'])
features = features.T
features

,Date,Weighted Volume Price,Total Volume
0,2014-07-23 19:00:00,605.64,0.0
1,2014-07-23 20:00:00,605.64,0.0
2,2014-07-23 21:00:00,605.64,624.12
3,2014-07-23 22:00:00,605.64,0.0
4,2014-07-23 23:00:00,605.64,0.0
...,...,...,...
44013,2019-07-31 16:00:00,10023.502496,13463506.17
44014,2019-07-31 17:00:00,10047.513868,7319068.22
44015,2019-07-31 18:00:00,10011.414322,7881541.11
44016,2019-07-31 19:00:00,10087.354734,13196955.01
44017,2019-07-31 20:00:00,10048.901044,18486394.17

In [22]:
filepath = "https://www.cryptodatadownload.com/cdd/gemini_BTCUSD_1hr.csv"
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
test_data = pd.read_csv(filepath, skiprows=1)
test_data = test_data.iloc[::-1] #reverse order from newest to oldest data to oldest to newest data
test_data.reset_index(drop=True, inplace=True)

In [23]:
print(test_data['Date'][33416]) #connect with the provided data

2019-07-31 21:00:00

In [24]:
test_data_2 = test_data.drop(['Unix Timestamp','Symbol','Open','High','Low'],axis=1)
test_data_2 = test_data_2.rename(columns={'Close': 'Weighted Volume Price', 'Volume': 'Total Volume'})
test_data_2

,Date,Weighted Volume Price,Total Volume
0,2015-10-08 13:00:00,245.00,0.606654
1,2015-10-08 14:00:00,245.00,4.453649
2,2015-10-08 15:00:00,244.92,3.016926
3,2015-10-08 16:00:00,244.25,3.895252
4,2015-10-08 17:00:00,244.99,3.920632
...,...,...,...
52156,2021-09-19 20:00:00,47611.24,8.765078
52157,2021-09-19 21:00:00,47462.97,14.128244
52158,2021-09-19 22:00:00,47062.74,67.722053
52159,2021-09-19 23:00:00,47258.42,29.666629
52160,2021-09-20 00:00:00,47088.24,13.295159

In [25]:
features = features.append(test_data_2.iloc[33416:,:]) #All data from training, validating and testing set
features = features.reset_index()

In [26]:
#MACD 
SMA_12 = features.rolling(window=12)['Weighted Volume Price'].mean()
multiplier_12 = 2/13
EMA_12 = multiplier_12*features['Weighted Volume Price']+(1-multiplier_12)*SMA_12.shift()

SMA_26 = features.rolling(window=26)['Weighted Volume Price'].mean()
multiplier_26 = 2/27
EMA_26 = multiplier_26*features['Weighted Volume Price']+(1-multiplier_26)*SMA_26.shift()

MACD = EMA_12-EMA_26
features['MACD'] = MACD

In [27]:
#1-7 hourly return
features['1 hour return'] = features['Weighted Volume Price'].pct_change(1)
features['2 hour return'] = features['Weighted Volume Price'].pct_change(2)
features['3 hour return'] = features['Weighted Volume Price'].pct_change(3)
features['4 hour return'] = features['Weighted Volume Price'].pct_change(4)
features['5 hour return'] = features['Weighted Volume Price'].pct_change(5)
features['6 hour return'] = features['Weighted Volume Price'].pct_change(6)
features['7 hour return'] = features['Weighted Volume Price'].pct_change(7)

In [28]:
#Moving average
features['50 hour moving average'] = features.rolling(window=50)['Weighted Volume Price'].mean()
features['200 hour moving average'] = features.rolling(window=200)['Weighted Volume Price'].mean()

In [29]:
#Rolling volatility
features['20 hour volatility'] = features['Weighted Volume Price'].rolling(window=20).std()
features['100 hour volatility'] = features['Weighted Volume Price'].rolling(window=100).std()
features['200 hour volatility'] = features['Weighted Volume Price'].rolling(window=200).std()

In [30]:
#RSI
def divbyzero(x,y): #create this function in the case where there is no negative return in 14 days period.
    if x == 0:
        a=0
    elif y ==0:
        a = 100
    else:
        a= x/y
    return a
RSI = np.zeros(features['Weighted Volume Price'].shape[0])

for x in range(RSI.shape[0]):
    if x <13:
        continue
    else:
        pos = features['Weighted Volume Price'][(x-14):x][features['1 hour return'][(x-14):x]>0].mean()
        neg = features['Weighted Volume Price'][(x-14):x][features['1 hour return'][(x-14):x]<0].mean()
        if np.isnan(pos)==1:
            pos = 0
        if np.isnan(neg)==1:
            neg = 0
                 
        rs = divbyzero(pos,neg)
        RSI[x]=100-100/(1+rs)

features['RSI'] = RSI
features

,index,Date,Weighted Volume Price,Total Volume,MACD,1 hour return,2 hour return,3 hour return,4 hour return,5 hour return,6 hour return,7 hour return,50 hour moving average,200 hour moving average,20 hour volatility,100 hour volatility,200 hour volatility,RSI
0,0,2014-07-23 19:00:00,605.64,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
1,1,2014-07-23 20:00:00,605.64,0.0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
2,2,2014-07-23 21:00:00,605.64,624.12,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
3,3,2014-07-23 22:00:00,605.64,0.0,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
4,4,2014-07-23 23:00:00,605.64,0.0,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62758,52156,2021-09-19 20:00:00,47611.24,8.765078,-206.33317,0.004731,-0.001103,0.005217,0.001267,-0.001277,0.000145,0.005579,47950.0724,46862.22930,322.314339,405.734854,1261.097061,50.128288
62759,52157,2021-09-19 21:00:00,47462.97,14.128244,-239.828433,-0.003114,0.001602,-0.004214,0.002086,-0.001851,-0.004387,-0.002970,47949.3274,46871.50640,328.108484,407.701572,1258.642984,50.088917
62760,52158,2021-09-19 22:00:00,47062.74,67.722053,-291.654067,-0.008432,-0.011520,-0.006844,-0.012611,-0.006364,-0.010268,-0.012783,47950.8222,46878.43345,354.245569,415.457556,1255.846961,50.062150
62761,52159,2021-09-19 23:00:00,47258.42,29.666629,-314.359615,0.004158,-0.004310,-0.007410,-0.002714,-0.008506,-0.002232,-0.006153,47950.3856,46886.79705,365.093627,419.296356,1252.760582,50.031380
62762,52160,2021-09-20 00:00:00,47088.24,13.295159,-310.491268,-0.003601,0.000542,-0.007895,-0.010985,-0.006306,-0.012076,-0.005825,47953.1378,46892.81590,383.843250,426.231433,1250.810954,50.044527

In [31]:
## Saving the dataframe
features.to_csv("/data/workspace_files/features_draft1.csv")

In [32]:
## Feature creation - bollinger band
## Currently creating a volatility band on 'n' hours
def get_bollinger_bands(prices, window_size):
    sma = prices.rolling(window_size).mean()
    std = prices.rolling(window_size).std()
    bollinger_up = sma + std*2
    bollinger_down = sma - std*2
    return bollinger_up, bollinger_down

temp_prices = features["Weighted Volume Price"]
features["bollinger_up_7hr"], features["bollinger_down_7hr"] = get_bollinger_bands(temp_prices, window_size=7)

In [33]:
## Create a boolean feature, indicating breach of bollinger bands
def bollinger_breach(cell):
    if cell["Weighted Volume Price"] > cell["bollinger_up_7hr"]:
        return 1
    elif cell["Weighted Volume Price"] < cell["bollinger_down_7hr"]:
        return -1
    else:
        return 0
features["bollinger_breach"] = features.apply(bollinger_breach, axis=1)

In [34]:
## Create stochastic oscillator indicator
def stochastic_oscillator(prices, window=14):
    high = prices.rolling(window).max()
    low = prices.rolling(window).min()
    # if high == low:
    #     stoch = 0
    # else:
    numerator = 100*(prices - low)
    denominator = (high - low)
    stoch = np.zeros(numerator.shape)
    for i in range(numerator.shape[0]):
        if denominator[i] != 0:
            stoch[i] = numerator[i]/ denominator[i]
        else:
            stoch[i] = 0
    return stoch

stoch = stochastic_oscillator(temp_prices)

In [35]:
features["stoch"] = stoch

In [36]:
features.sample(5)

,index,Date,Weighted Volume Price,Total Volume,MACD,1 hour return,2 hour return,3 hour return,4 hour return,5 hour return,...,50 hour moving average,200 hour moving average,20 hour volatility,100 hour volatility,200 hour volatility,RSI,bollinger_up_7hr,bollinger_down_7hr,bollinger_breach,stoch
43197,43197,2019-06-27 16:00:00,10678.10179,84183187.22,-747.282379,-0.013720,-0.028469,-0.012389,-0.019255,-0.082195,...,12253.639507,10816.855872,736.772340,836.867105,1105.502103,50.151973,12053.654719,10159.726770,0,0.000000
48031,37429,2020-01-15 05:00:00,8598.88,27.528541,90.533355,0.001870,-0.014717,-0.023016,-0.019340,-0.021069,...,8405.366600,8120.665200,105.013405,248.090396,259.189814,50.194229,8923.269247,8530.987896,0,6.573020
54142,43540,2020-09-25 20:00:00,10722.74,67.957952,-16.593084,0.000275,0.000919,0.001703,0.006335,0.006188,...,10525.537400,10708.498750,44.165794,134.046923,248.160542,50.156416,10764.703233,10604.633910,0,100.000000
46645,36043,2019-11-18 09:00:00,8467.03,13.326805,-25.290399,0.000252,0.003094,0.003513,-0.000786,-0.000856,...,8493.309400,8656.589300,39.929763,67.141170,158.898589,50.034226,8494.978571,8429.481429,0,26.174497
15838,15838,2016-05-13 17:00:00,456.256356,52873.65,0.2499,0.000797,0.000447,0.002689,0.000035,0.000666,...,455.098214,456.904630,1.004797,2.068971,3.717719,50.043680,456.725530,454.970842,0,31.921438

In [37]:
# feature selection
from sklearn.feature_selection import mutual_info_regression
X_data = features.set_index('Date')
cols = ['Weighted Volume Price', 'Total Volume', 'MACD',
       '1 hour return', '2 hour return', '3 hour return', '4 hour return',
       '5 hour return', '6 hour return', '7 hour return',
       '50 hour moving average', '200 hour moving average',
       '20 hour volatility', '100 hour volatility', '200 hour volatility',
       'RSI', 'bollinger_up_7hr', 'bollinger_down_7hr', 'bollinger_breach',
       'stoch']
X_data = X_data[199:]
X_data = X_data[cols]
target = (X_data['Weighted Volume Price'].shift(-7)/X_data['Weighted Volume Price'] - 1).iloc[:-7]
X_data = X_data.iloc[:-7]
assert (target.index == X_data.index).all()

threshold = 10
feature_scores = mutual_info_regression(X_data, target, random_state=0)
high_score_features = []
for score, f_name in sorted(zip(feature_scores, X_data.columns), reverse=True)[:threshold]:
    print(f_name, score)
    high_score_features.append(f_name)

high_score_features

Weighted Volume Price 0.2810428448196367
200 hour moving average 0.24601856195926786
50 hour moving average 0.2352369961181413
bollinger_up_7hr 0.22966131187551042
bollinger_down_7hr 0.22506012614009663
RSI 0.18459493814482997
200 hour volatility 0.18337457340266727
7 hour return 0.18160330214411768
6 hour return 0.17370436272466172
5 hour return 0.1653788584987259

['Weighted Volume Price',
 '200 hour moving average',
 '50 hour moving average',
 'bollinger_up_7hr',
 'bollinger_down_7hr',
 'RSI',
 '200 hour volatility',
 '7 hour return',
 '6 hour return',
 '5 hour return']

In [38]:
high_score_features.append('Date')
ten_feature_set = features[high_score_features]
ten_feature_set.to_csv('/data/workspace_files/ten_feature_set.csv', index=False)

In [39]:
np.correlate(features)

TypeError: TypeError: _correlate_dispatcher() missing 1 required positional argument: 'v'